#!/bin/bash
# only run if changing branches, not if checking out a specific file
if [ $3 == '1' ]; then
	if [ "x$1" != "x$2" ]; then
		# Run sync and then omit Ctrl+C
		echo "Rsyncing with remote"
		~/dotfiles/nvim.appimage +:ARsyncUp --headless
	fi
fi
